package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strconv"
	"strings"

	"github.com/AeonDave/go-donut/donut"
	"github.com/akamensky/argparse"
)

func main() {
	if err := run(os.Args); err != nil {
		log.Println(err)
		os.Exit(1)
	}
	log.Println("Done!")
}

func run(args []string) error {
	parser := argparse.NewParser("go-donut", "Convert a VBS/JS or PE/.NET EXE/DLL to shellcode.\n\t\t"+
		"Only the finest artisanal donuts are made of shells.")

	// -MODULE OPTIONS-
	moduleName := parser.String("n", "module", &argparse.Options{Required: false,
		Help: "Module name. Randomly generated by default with entropy enabled."})
	url := parser.String("u", "url", &argparse.Options{Required: false,
		Help: "HTTP server that will host the donut module."})
	entropy := parser.Int("e", "entropy", &argparse.Options{Required: false, Default: 2,
		Help: "Entropy. 1=disable, 2=use random names (default)"})

	//  -PIC/SHELLCODE OPTIONS-
	archStr := parser.String("a", "arch", &argparse.Options{Required: false,
		Default: "x84", Help: "Target Architecture: x32, x64, or x84"})
	bypass := parser.Int("b", "bypass", &argparse.Options{Required: false,
		Default: 3, Help: "Bypass AMSI/WLDP : 1=skip, 2=abort on fail, 3=continue on fail."})
	dstFile := parser.String("o", "out", &argparse.Options{Required: false,
		Default: "loader.bin", Help: "Output file."})
	format := parser.Int("f", "format", &argparse.Options{Required: false,
		Default: 1, Help: "Output format. 0 or 1=raw (the only supported format)"})
	oepString := parser.String("y", "oep", &argparse.Options{Required: false,
		Help: "Create a new thread for loader. Optionally execute original entrypoint of host process."})
	action := parser.Int("x", "exit", &argparse.Options{Required: false,
		Default: 1, Help: "Exiting. 1=exit thread, 2=exit process"})

	//  -FILE OPTIONS-
	className := parser.String("c", "class", &argparse.Options{Required: false,
		Help: "Optional class name.  (required for .NET DLL)"})
	appDomain := parser.String("d", "domain", &argparse.Options{Required: false,
		Help: "AppDomain name to create for .NET.  Randomly generated by default with entropy enabled."})
	method := parser.String("m", "method", &argparse.Options{Required: false,
		Help: "Optional method or API name for DLL. (a method is required for .NET DLL)"})
	params := parser.String("p", "params", &argparse.Options{Required: false,
		Help: "Optional parameters/command line inside quotations for DLL method/function or EXE."})
	wFlag := parser.Flag("w", "unicode", &argparse.Options{Required: false,
		Help: "Command line is passed to unmanaged DLL function in UNICODE format. (default is ANSI)"})
	runtime := parser.String("r", "runtime", &argparse.Options{Required: false,
		Help: "CLR runtime version. This will override the auto-detected version."})
	tFlag := parser.Flag("t", "thread", &argparse.Options{Required: false,
		Help: "Create new thread for entrypoint of unmanaged EXE."})
	zFlag := parser.Int("z", "compress", &argparse.Options{Required: false, Default: 1,
		Help: "Pack/Compress file. 0 or 1=disable (the only supported mode)"})

	// go-donut only flags
	srcFile := parser.String("i", "in", &argparse.Options{Required: true,
		Help: ".NET assembly, EXE, DLL, VBS, JS or XSL file to execute in-memory."})

	morphFlag := parser.Flag("", "morph", &argparse.Options{Required: false,
		Help: "Enable polymorphic mutation of loader stub. Randomize the loader byte representation across builds."})
	verbose := parser.Flag("v", "verbose", &argparse.Options{Required: false, Help: "Show verbose output."})

	if err := parser.Parse(args); err != nil {
		return fmt.Errorf("%s", parser.Usage(err))
	}
	if *srcFile == "" {
		return fmt.Errorf("%s", parser.Usage(fmt.Errorf("no source file provided")))
	}
	if err := validateOptionValues(*entropy, *zFlag, *format); err != nil {
		return err
	}

	oep, err := parseOEP(*oepString)
	if err != nil {
		return fmt.Errorf("invalid OEP: %w", err)
	}

	var donutArch donut.DonutArch
	switch strings.ToLower(*archStr) {
	case "x32", "386":
		donutArch = donut.X32
	case "x64", "amd64":
		donutArch = donut.X64
	case "x84":
		donutArch = donut.X84
	default:
		return fmt.Errorf("unknown architecture provided")
	}

	config := new(donut.DonutConfig)
	config.Arch = donutArch
	config.Entropy = uint32(*entropy)
	config.OEP = oep

	if *url == "" {
		config.InstType = donut.DONUT_INSTANCE_PIC
	} else {
		config.InstType = donut.DONUT_INSTANCE_URL
	}

	config.Parameters = *params
	config.Runtime = *runtime
	config.URL = *url
	config.Class = *className
	config.Method = *method
	config.Domain = *appDomain
	config.Bypass = *bypass
	config.ModuleName = *moduleName
	config.Compress = uint32(*zFlag)
	config.Format = uint32(*format)
	config.Verbose = *verbose

	if *tFlag {
		config.Thread = 1
	}
	if *wFlag { // convert command line to unicode? only applies to unmanaged DLL function
		config.Unicode = 1
	}
	config.Morph = *morphFlag
	config.ExitOpt = uint32(*action)

	return generateAndWrite(*srcFile, *url, *dstFile, config)
}

func validateOptionValues(entropy, compress, format int) error {
	if entropy != int(donut.DONUT_ENTROPY_NONE) && entropy != int(donut.DONUT_ENTROPY_RANDOM) {
		return fmt.Errorf("unsupported entropy %d: supported values are 1 (none) and 2 (random names)", entropy)
	}
	if compress != 0 && compress != 1 {
		return fmt.Errorf("unsupported compression %d: supported values are 0 or 1 (none)", compress)
	}
	if format != 0 && format != 1 {
		return fmt.Errorf("unsupported format %d: only raw output is supported (use 0 or 1)", format)
	}
	return nil
}

func generateAndWrite(srcFile, url, dstFile string, config *donut.DonutConfig) (err error) {
	if srcFile == "" {
		if url == "" {
			return fmt.Errorf("no source URL or file provided")
		}
		payload, err := donut.ShellcodeFromURL(url, config)
		if err != nil {
			return err
		}
		return ioutil.WriteFile(dstFile, payload.Bytes(), 0644)
	}

	payload, err := donut.ShellcodeFromFile(srcFile, config)
	if err != nil {
		return err
	}

	f, err := os.Create(dstFile)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := f.Close(); err == nil {
			err = closeErr
		}
	}()
	_, err = payload.WriteTo(f)
	return err
}

// parseOEP accepts the hexadecimal OEP offset used by the Donut CLI. Donut v1.1
// stores this value in a 32-bit instance field, so accepting a larger CLI value
// would silently truncate the generated loader configuration.
func parseOEP(value string) (uint32, error) {
	if value == "" {
		return 0, nil
	}

	parsed, err := strconv.ParseUint(value, 16, 64)
	if err != nil {
		return 0, err
	}
	if parsed > uint64(^uint32(0)) {
		return 0, fmt.Errorf("%#x exceeds the 32-bit Donut OEP field", parsed)
	}
	return uint32(parsed), nil
}
